### ISSUE TITLE
auro-accordion: no carat icon

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-accordion#25] opened 2021-08-11 21:24 UTC
## Is your feature request related to a problem? Please describe.
In instances where a component disconnected from the auro-accordion triggers the expansion attribute change, we would like a way to hide the carat as that is not the intended place for a guest to click.

![image](https://user-images.githubusercontent.com/7005799/129105378-0a50cc5c-46de-4c7f-9752-990495fb0e35.png)

## Describe the solution you'd like
Attribute hides the icon.

## Describe alternatives you've considered
Turning the icon into a slot and allowing any (or no) icon in it.

**Comment by geoffrich** [comment] 2021-08-11 21:29
Is this a dupe of #24?

**Closed** 2021-08-11 21:57 UTC
Labels: duplicate, Type: Feature, not-reviewed
